[phases.setup]
nixPkgs = [
"python311",
"nodejs",
"glib",
"nss",
"atk",
"at-spi2-atk",
"cups",
"drm",
"dbus",
"expat",
"xcbutil",
"libxkbcommon",
"mesa"
]

[phases.install]
cmds = [
"pip install -r requirements.txt",
"playwright install chromium"
]

[start]
cmd = "gunicorn app:app"
